all: main.cpp carte.cpp joueur.cpp deck.cpp jeu.cpp outils.cpp combinaison.cpp vecteur.h
	g++ -Wall -o main.out main.cpp carte.cpp joueur.cpp deck.cpp jeu.cpp outils.cpp combinaison.cpp vecteur.h

clean:
	rm -rf *.o

mrproper:
	rm -f main
