INSERT INTO SAGAS VALUES('S001', 'Alien',null);

INSERT INTO EPISODES VALUES('F003','S001',1);

INSERT INTO EPISODES VALUES('F002','S001',1);

ALTER TABLE SAGAS ADD NB_EPIS NUMBER;

UPDATE SAGAS S SET NB_EPIS=(SELECT COUNT(*) FROM EPISODES E WHERE E.COD_SAGA=S.COD_SAGA);

ALTER TABLE PERSONNAGES ADD NB_PROD  NUMBER;

UPDATE PERSONNAGES S SET NB_PROD=(SELECT COUNT(CODPROD) FROM JOUENT J WHERE S.COD_PERS=J.COD_PERS);
