INSERT INTO REALISATEURS VALUES ('0', 'James Cameron', 'Canadien', '16/08/1954', NULL);
INSERT INTO REALISATEURS VALUES ('1', 'Ridley Scott', 'Anglais', '30/11/1937', NULL);
INSERT INTO REALISATEURS VALUES ('2', 'Sam Mendes', 'Anglais', '01/08/1965', NULL);
INSERT INTO REALISATEURS VALUES ('3', 'Jean Negulesco', 'Américain', '26/02/1900', '18/07/1993');
INSERT INTO REALISATEURS VALUES ('4', 'Guillaume Canet', 'Français', '10/04/1973', NULL);
INSERT INTO REALISATEURS VALUES ('5', 'Claude Berry', 'Français', '01/07/1934', '12/01/2009');
INSERT INTO REALISATEURS VALUES ('6', 'Danny Boyle', 'Anglais', '20/10/1956', NULL);
INSERT INTO REALISATEURS VALUES ('7', 'Gilles Lelouche', 'Français', '05/07/1972', NULL);

INSERT INTO ACTEURS VALUES ('0', 'Worthington', 'Sam', 'Australien', 'm', '02/08/1976', NULL);
INSERT INTO ACTEURS VALUES ('1', 'Saldana', 'Zoe', 'Américain', 'f', '19/06/1978', NULL);
INSERT INTO ACTEURS VALUES ('2', 'Weaver', 'Sigourney', 'Américain', 'f', '08/10/1949', NULL);
INSERT INTO ACTEURS VALUES ('3', 'Lang', 'Stephen', 'Américain', 'm', '11/07/1952', NULL);
INSERT INTO ACTEURS VALUES ('4', 'Biehn', 'Michael', 'Américain', 'm', '31/07/1956', NULL);
INSERT INTO ACTEURS VALUES ('5', 'Henriksen', 'Lance', 'Américain', 'm', '05/05/1940', NULL);
INSERT INTO ACTEURS VALUES ('6', 'Skerritt', 'Tom', 'Américain', 'm', '25/08/1933', NULL);
INSERT INTO ACTEURS VALUES ('7', 'Di Caprio', 'Leonardo', 'Américain', 'm', '11/11/1974', NULL);
INSERT INTO ACTEURS VALUES ('8', 'Winslet', 'Kate', 'Anglais', 'f', '05/10/1975', NULL);
INSERT INTO ACTEURS VALUES ('9', 'Webb', 'Clifton', 'Américain', 'm', '11/11/1889', '13/10/1966');
INSERT INTO ACTEURS VALUES ('10', 'Stanwick', 'Barbara', 'Américain', 'f', '16/07/1907', '20/01/1990');
INSERT INTO ACTEURS VALUES ('11', 'Dalton', 'Audrey', 'Américain', 'f', '20/01/1934', NULL);
INSERT INTO ACTEURS VALUES ('12', 'Wagner', 'Robert', 'Américain', 'm', '10/02/1930', NULL);
INSERT INTO ACTEURS VALUES ('13', 'Cluzet', 'François', 'Français', 'm', '21/09/1955', NULL);
INSERT INTO ACTEURS VALUES ('14', 'Cotillard', 'Marion', 'Français', 'f', '30/09/1975', NULL);
INSERT INTO ACTEURS VALUES ('15', 'Dujardin', 'Jean', 'Français', 'm',  '19/06/1972', NULL);
INSERT INTO ACTEURS VALUES ('16', 'Lellouche', 'Gilles', 'Français', 'm', '19/06/1972', NULL);
INSERT INTO ACTEURS VALUES ('17', 'Magimel', 'Benoit', 'Français', 'm', '11/05/1974', NULL);
INSERT INTO ACTEURS VALUES ('18', 'Canet', 'Guillaume', 'Français' , 'm', '10/04/1973', NULL);
INSERT INTO ACTEURS VALUES ('19', 'Tautou', 'Audrey', 'Français', 'f', '09/08/1976', NULL);
INSERT INTO ACTEURS VALUES ('20', 'Ledoyen', 'Virginie', 'Français', 'f', '15/11/1975', NULL);
INSERT INTO ACTEURS VALUES ('21', 'Poelvoorde', 'Benoit', 'Belge', 'm', '22/09/1964', NULL);

INSERT INTO FILMS VALUES ('0', 'Avatar', '16/12/2009', 162, NULL, '0');
INSERT INTO FILMS VALUES ('2', 'Aliens, Le Retour', '08/10/1986', 137, NULL, '0');
INSERT INTO FILMS VALUES ('3', 'Alien, Le Huitième Passager', '12/09/1979', 116, NULL, '1');
INSERT INTO FILMS VALUES ('4', 'Titanic', '07/07/1998', 194 ,NULL, '0');
INSERT INTO FILMS VALUES ('5', 'Les Noces Rebelles', '21/01/2009', 125, NULL , '2');
INSERT INTO FILMS VALUES ('6', 'Titanic', NULL, 98, NULL, '3');
INSERT INTO FILMS VALUES ('7', 'Les Petits Mouchoirs', '20/10/2010', 154, NULL, '4');
INSERT INTO FILMS VALUES ('8', 'Ensemble c''est tout', '21/03/2007', 97, NULL, '5');
INSERT INTO FILMS VALUES ('9', 'La Plage', '16/02/2000', 119, NULL, '6');
INSERT INTO FILMS VALUES ('10', 'Narco', '01/12/2004', 105, NULL, '7');

INSERT INTO JOUENT VALUES ('0','0', 'Jake Sully');
INSERT INTO JOUENT VALUES ('0','1', 'Neytiri');
INSERT INTO JOUENT VALUES ('0', '2','Grace Augustin');
INSERT INTO JOUENT VALUES ('0','3','Colonel Miles');
INSERT INTO JOUENT VALUES ('2','2','Lieutenant Ellen Repley');
INSERT INTO JOUENT VALUES ('2', '4', 'Caporal Dwayne Hicks');
INSERT INTO JOUENT VALUES ('2', '5', 'Êveque');
INSERT INTO JOUENT VALUES ('3', '2', 'Lieutenant Ellen Repley');
INSERT INTO JOUENT VALUES ('3','6','Capitaine A.J. Dallas');
INSERT INTO JOUENT VALUES ('4','7','Jack Dawson');
INSERT INTO JOUENT VALUES ('4','8','Rose DeWitt Butaker');
INSERT INTO JOUENT VALUES ('5','7','Franck Wheeler');
INSERT INTO JOUENT VALUES ('5', '8', 'April Wheeler');
INSERT INTO JOUENT VALUES ('6','9', 'Richard Ward Sturges');
INSERT INTO JOUENT VALUES ('6','10', 'Julia Sturges');
INSERT INTO JOUENT VALUES ('6', '11', 'Anette Sturges');
INSERT INTO JOUENT VALUES ('6', '12', 'Gifford Roger');
INSERT INTO JOUENT VALUES ('7','13', 'Max Cantara');
INSERT INTO JOUENT VALUES ('7','14', 'Marie');
INSERT INTO JOUENT VALUES ('7','15', 'Ludo');
INSERT INTO JOUENT VALUES ('7','16', 'Eric');
INSERT INTO JOUENT VALUES ('7','17', 'Vincent Ribaud');
INSERT INTO JOUENT VALUES ('8', '18', 'Franck');
INSERT INTO JOUENT VALUES ('8', '19', 'Camille');
INSERT INTO JOUENT VALUES ('9', '7', 'Richard');
INSERT INTO JOUENT VALUES ('9', '18', 'Etienne');
INSERT INTO JOUENT VALUES ('9', '20', 'Françoise');
INSERT INTO JOUENT VALUES ('10', '18', 'Gustave Klopp');
INSERT INTO JOUENT VALUES ('10', '21', 'Lenny Bar');
INSERT INTO JOUENT VALUES ('10', '16', 'Le Jumeau Patineur');
