all: main.cpp ensemble.h adherent.cpp adresse.cpp exemplaire.cpp adherents.cpp
	g++ -Wall -o main main.cpp ensemble.h adherent.cpp adresse.cpp exemplaire.cpp adherents.cpp

clean:
	rm -rf *.o

mrproper:
	rm -f main
