all: main.cpp adherent.cpp adresse.cpp exemplaire.cpp adherents.cpp oeuvre.cpp oeuvres.cpp
	g++ -Wall -o TP6.out main.cpp adherent.cpp adresse.cpp exemplaire.cpp adherents.cpp oeuvre.cpp oeuvres.cpp

clean:
	rm -rf *.o

mrproper:
	rm -f main
