SELECT*
  FROM FILMS
  WHERE BUDGET>1000000 ;
SELECT*
  FROM ACTEURS
  WHERE NATIONACT='Américain'
        AND SEXE='f';
SELECT NOMACT, PRENOMACT
  FROM ACTEURS
  WHERE NATIONACT='Français'
        OR NATIONACT='Belge';
SELECT TITREFILM
  FROM REALISATEURS, FILMS
  WHERE NOMREAL='Cameron'
        AND PRENOMREAL='James'
        AND REALISATEURS.CODREAL=FILMS.CODREAL;
SELECT 
