var articles = [
  {
    'ref':'pr',
    'nom':'Poivrons rouges',
    'catégorie' : 'légume',
    'photos':[
      {
        'url':'fruits_legumes_1.jpg',
        'type':'sprite',
        'x': 15,
        'y':16,
        'w':163,
        'h':112,
      },
    ],
  },
  {
    'ref':'pj',
    'nom':'Poivrons jaunes',
    'catégorie' : 'légume',
    'photos':[
      {
        'url':'fruits_legumes_2.jpg',
        'type':'sprite',
        'x': 8,
        'y':141,
        'w':183,
        'h':146,
      },
    ],
  },
  {
    'ref':'po',
    'nom':'Poivrons oranges',
    'catégorie' : 'légume',
    'photos':[
      {
        'url':'fruits_legumes_2.jpg',
        'type':'sprite',
        'x': 8,
        'y':141,
        'w':183,
        'h':146,
      },
    ],
  },
  {
    'ref':'or',
    'nom':'Oranges',
    'catégorie' : 'fruit',
    'photos':[
      {
        'url':'fruits_legumes_1.jpg',
        'type':'sprite',
        'x': 375,
        'y':25,
        'w':130,
        'h':116,
      },
      {
        'url':'fruits_legumes_2.jpg',
        'type':'sprite',
        'x': 14,
        'y':427,
        'w':202,
        'h':132,
      },
    ],
  },
  {
    'ref':'av',
    'nom':'Avocats',
    'catégorie' : 'légume',
    'photos':[
      {
        'url':'fruits_legumes_1.jpg',
        'type':'sprite',
        'x': 484,
        'y':514,
        'w':143,
        'h':124,
      },
      {
        'url':'fruits_legumes_2.jpg',
        'type':'sprite',
        'x': 403,
        'y':22,
        'w':189,
        'h':111,
      },
    ],
  },
  {
    'ref':'fr',
    'nom':'Fraises',
    'catégorie' : 'fruit',
    'photos':[
      {
        'url':'fruits_legumes_2.jpg',
        'type':'sprite',
        'x':424,
        'y':420,
        'w':188,
        'h':140,
      },
      {
        'url':'fruits_legumes_1.jpg',
        'type':'sprite',
        'x':25,
        'y':639,
        'w':118,
        'h':135,
      },
    ],
  },
  {
    'ref':'pa',
    'nom':'Pamplemousses',
    'catégorie' : 'fruit',
    'photos':[
      {
        'url':'fruits_legumes_2.jpg',
        'type':'sprite',
        'x':208,
        'y':4,
        'w':189,
        'h':144,
      },
      {
        'url':'fruits_legumes_1.jpg',
        'type':'sprite',
        'x': 489,
        'y':147,
        'w':120,
        'h':127,
      },
      {
        'url':'fruits_legumes_1.jpg',
        'type':'sprite',
        'x':349,
        'y':511,
        'w':132,
        'h':128,
      },
    ],
  },
  {
    'ref':'bi',
    'nom':'Bière',
    'catégorie' : 'boisson',
    'photos':[
      {
        'url':'fruits_legumes_2.jpg',
        'type':'sprite',
        'x': 8,
        'y':141,
        'w':183,
        'h':146,
      },
    ],
  },
]
