ALTER TABLE CATEGORIES ADD COD_PARENT CHAR(4);

ALTER TABLE CATEGORIES ADD CONSTRAINT FK_CATEGORIE FOREIGN KEY(COD_PARENT) REFERENCES CATEGORIES;

SELECT COD_CAT, NOM_CAT
  FROM CATEGORIES
  START WITH NOM_CAT='Action'
  CONNECT BY COD_PARENT=PRIOR COD_CAT;

SELECT CODFILM, TITRE
  FROM FILMS
  WHERE COD_CAT IN SELECT COD_CAT, NOM_CAT
                      FROM CATEGORIES
                        START WITH NOM_CAT='Action'
                        CONNECT BY COD_PARENT=PRIOR COD_CAT; 
