ALTER TABLE FILMS MODIFY (TITREFILM VARCHAR(70));
ALTER TABLE REALISATEURS ADD (PRENOMREAL VARCHAR(50));

UPDATE REALISATEURS SET NOMREAL='Cameron', PRENOMREAL='James' WHERE CODREAL='0';
UPDATE REALISATEURS SET NOMREAL='Scott', PRENOMREAL='Ridley' WHERE CODREAL='1';
UPDATE REALISATEURS SET NOMREAL='Mendes', PRENOMREAL='Sam' WHERE CODREAL='2';
UPDATE REALISATEURS SET NOMREAL='Negulesco', PRENOMREAL='Jean' WHERE CODREAL='3';
UPDATE REALISATEURS SET NOMREAL='Canet', PRENOMREAL='Guillaume' WHERE CODREAL='4';
UPDATE REALISATEURS SET NOMREAL='Berry', PRENOMREAL='Claude' WHERE CODREAL='5';
UPDATE REALISATEURS SET NOMREAL='Boyle', PRENOMREAL='Danny' WHERE CODREAL='6';
UPDATE REALISATEURS SET NOMREAL='Lelouche', PRENOMREAL='Gilles' WHERE CODREAL='7';

UPDATE FILMS SET BUDGET=345600000 WHERE CODFILM='0';
UPDATE FILMS SET BUDGET=123456 WHERE CODFILM='2';
UPDATE FILMS SET BUDGET=32122 WHERE CODFILM='3';
UPDATE FILMS SET BUDGET=67889008 WHERE CODFILM='4';
UPDATE FILMS SET BUDGET=563215 WHERE CODFILM='5';
UPDATE FILMS SET BUDGET=12309 WHERE CODFILM='6';
UPDATE FILMS SET BUDGET=8765432 WHERE CODFILM='7';
UPDATE FILMS SET BUDGET=542987 WHERE CODFILM='8';
UPDATE FILMS SET BUDGET=296306 WHERE CODFILM='9';
UPDATE FILMS SET BUDGET=328764 WHERE CODFILM='10';

UPDATE FILMS SET BUDGET=BUDGET+BUDGET*0.1;

ALTER TABLE FILMS ADD (CATEGORIE VARCHAR(50));
ALTER TABLE FILMS MODIFY (CATEGORIE VARCHAR(50) CONSTRAINT CK_CATEGORIE CHECK(CATEGORIE='Science-Fiction' OR CATEGORIE='Drame' OR CATEGORIE='Comédie Dramatique' OR CATEGORIE='Thriller' OR CATEGORIE='Comédie'));

UPDATE FILMS SET CATEGORIE='Science-Fiction' WHERE CODFILM='0';
UPDATE FILMS SET CATEGORIE='Science-Fiction' WHERE CODFILM='2';
UPDATE FILMS SET CATEGORIE='Science-Fiction' WHERE CODFILM='3';
UPDATE FILMS SET CATEGORIE='Drame' WHERE CODFILM='4';
UPDATE FILMS SET CATEGORIE='Drame' WHERE CODFILM='5';
UPDATE FILMS SET CATEGORIE='Drame' WHERE CODFILM='6';
UPDATE FILMS SET CATEGORIE='Comédie Dramatique' WHERE CODFILM='7';
UPDATE FILMS SET CATEGORIE='Comédie Dramatique' WHERE CODFILM='8';
UPDATE FILMS SET CATEGORIE='Thriller' WHERE CODFILM='9';
UPDATE FILMS SET CATEGORIE='Comédie' WHERE CODFILM='10';
