CREATE TABLE CATEGORIES(
	COD_CAT CHAR(4),
	NOM_CAT VARCHAR(50),
  CONSTRAINT PK_CATEGORIE PRIMARY KEY(COD_CAT));

CREATE TABLE PRODUCT_CINE(
	COD_PROD CHAR(4),
	COD_CAT CHAR(4),
	TITRE VARCHAR(50),
	DUREE NUMBER(),
	DATE_SORTIE DATE,
  BUDGET NUMBER(),
	CONSTRAINT PK_PRODUCT_CINE PRIMARY KEY(COD_PROD),
	CONSTRAINT FK_COD_CAT_CATEGORIES FOREIGN KEY(COD_CAT) REFERENCES CATEGORIES);

CREATE TABLE FILM_ANIM(
	COD_PROD CHAR(4),
	COD_CAT CHAR(4),
  TITRE VARCHAR(50),
	DUREE NUMBER,
	DATE_SORTIE DATE,
  BUDGET NUMBER,
  SOC_ANIM VARCHAR(50),
  TYPE_ANIM VARCHAR(50),
	CONSTRAINT PK_FILM_ANIM PRIMARY KEY(COD_PROD),
	CONSTRAINT FK_COD_PROD_PRODUCT_CINE FOREIGN KEY(COD_PROD) REFERENCES PRODUCT_CINE,
  CONSTRAINT FK_COD_CAT_CATEGORIES_ANIM FOREIGN KEY(COD_CAT) REFERENCES CATEGORIES);

CREATE TABLE FILMS (
  COD_PROD CHAR(4),
  COD_CAT CHAR(4),
  TITRE VARCHAR(50),
  DUREE NUMBER,
  DATESORTIE DATE,
  BUDGET NUMBER,
  DATE_DEB_TOUR DATE,
  DATE_FIN_TOUR DATE,
  CONSTRAINT PK_FILMS PRIMARY KEY(COD_PROD),
  CONSTRAINT FK_COD_CAT_CATEGORIES_FILMS FOREIGN KEY (COD_CAT) REFERENCES CATEGORIES,
  CONSTRAINT FK_COD_PROD_PRODUCT_CINE_FILMS FOREIGN KEY (COD_PROD) REFERENCES CATEGORIES);

CREATE TABLE SAGAS(
  COD_SAGA CHAR(4),
  NOM_SAGA VARCHAR(50),
  CONSTRAINT PK_SAGA PRIMARY KEY(COD_SAGA));

CREATE TABLE EPISODES(
  COD_PROD CHAR(4),
  COD_SAGA CHAR(4),
  NUM_EPISODE NUMBER,
  CONSTRAINT PK_EPISODES PRIMARY KEY(COD_PROD),
  CONSTRAINT FK_COD_PROD_PRODUCT_CINE_EP FOREIGN KEY(COD_PROD) REFERENCES PRODUCT_CINE,
  CONSTRAINT FK_COD_SAGA_SAGAS FOREIGN KEY(COD_SAGAS) REFERENCES SAGA);
)

CREATE OR REPLACE TRIGGER INSERTDFILMS
BEFORE INSERT ON FILMS
FOR EACH ROW
BEGIN
    INSERT INTO PRODUCT_CINE VALUES (
    :NEW.COD_PROD, :NEW.COD_CAT, :NEW.TITRE, 
    :NEW.DUREE, :NEW.DATE_SORTIE, :NEW.BUDGET);
END;

CREATE OR REPLACE TRIGGER INSERTDFILM_ANIM
BEFORE INSERT ON FILM_ANIM
FOR EACH ROW
BEGIN
    INSERT INTO PRODUCT_CINE VALUES (
    :NEW.COD_PROD, :NEW.COD_CAT, :NEW.TITRE,
    :NEW.DUREE, :NEW.DATE_SORTIE, :NEW.BUDGET);
END;

CREATE OR REPLACE TRIGGER DELETEDFILMS
AFTER DELETE ON FILMS
FOR EACH ROW
BEGIN
    DELETE FROM PRODUCT_CINE WHERE COD_PROD = :OLD.COD_PROD;
END;

CREATE OR REPLACE TRIGGER DELETEDFILM_ANIM
AFTER DELETE ON FILM_ANIM
FOR EACH ROW
BEGIN
    DELETE FROM PRODUCT_CINE WHERE COD_PROD = :OLD.COD_PROD;
END;

  CREATE VIEW NOM_VUE AS req;
