CREATE TABLE CATEGORIES(
	COD_CAT CHAR(4),
	NOM_CAT VARCHAR(50),
  CONSTRAINT PK_CATEGORIE PRIMARY KEY(COD_CAT));

CREATE TABLE PRODUCT_CINE(
	COD_PROD CHAR(4),
	COD_CAT CHAR(4),
	TITRE VARCHAR(50),
	DUREE NUMBER(),
	DATE_SORTIE DATE,
  BUDGET NUMBER(),
	CONSTRAINT PK_PRODUCT_CINE PRIMARY KEY(COD_PROD),
	CONSTRAINT FK_COD_CAT_CATEGORIES FOREIGN KEY(COD_CAT) REFERENCES CATEGORIES);

CREATE TABLE FILM_ANIM(
	COD_PROD CHAR(4),
	COD_CAT CHAR(4),
  TITRE VARCHAR(50),
	DUREE NUMBER,
	DATE_SORTIE DATE,
  BUDGET NUMBER,
  SOC_ANIM VARCHAR(50),
  TYPE_ANIM VARCHAR(50),
	CONSTRAINT PK_FILM_ANIM PRIMARY KEY(COD_PROD),
	CONSTRAINT FK_COD_PROD_PRODUCT_CINE FOREIGN KEY(COD_PROD) REFERENCES PRODUCT_CINE,
  CONSTRAINT FK_COD_CAT_CATEGORIES_ANIM FOREIGN KEY(COD_CAT) REFERENCES CATEGORIES);

CREATE TABLE FILMS (
  COD_PROD CHAR(4),
  COD_CAT CHAR(4),
  TITRE VARCHAR(50),
  DUREE NUMBER,
  DATE_SORTIE DATE,
  BUDGET NUMBER,
  DATE_DEB_TOUR DATE,
  DATE_FIN_TOUR DATE,
  CONSTRAINT PK_FILMS PRIMARY KEY(COD_PROD),
  CONSTRAINT FK_COD_CAT_CATEGORIES_FILMS FOREIGN KEY (COD_CAT) REFERENCES CATEGORIES,
  CONSTRAINT FK_COD_PROD_PRODUCT_CINE_FILMS FOREIGN KEY (COD_PROD) REFERENCES PRODUCT_CINE);

CREATE TABLE SAGAS(
  COD_SAGA CHAR(4),
  NOM_SAGA VARCHAR(50),
  CONSTRAINT PK_SAGA PRIMARY KEY(COD_SAGA));

CREATE TABLE EPISODES(
  COD_PROD CHAR(4),
  COD_SAGA CHAR(4),
  NUM_EPISODE NUMBER,
  CONSTRAINT PK_EPISODES PRIMARY KEY(COD_PROD),
  CONSTRAINT FK_COD_PROD_PRODUCT_CINE_EP FOREIGN KEY(COD_PROD) REFERENCES PRODUCT_CINE,
  CONSTRAINT FK_COD_SAGA_SAGAS FOREIGN KEY(COD_SAGAS) REFERENCES SAGA);
)

CREATE OR REPLACE TRIGGER INSERTDFILMS
BEFORE INSERT ON FILMS
FOR EACH ROW
BEGIN
    INSERT INTO PRODUCT_CINE VALUES (
    :NEW.COD_PROD, :NEW.COD_CAT, :NEW.TITRE,
    :NEW.DUREE, :NEW.DATE_SORTIE, :NEW.BUDGET);
END;

CREATE OR REPLACE TRIGGER INSERTDFILM_ANIM
BEFORE INSERT ON FILM_ANIM
FOR EACH ROW
BEGIN
    INSERT INTO PRODUCT_CINE VALUES (
    :NEW.COD_PROD, :NEW.COD_CAT, :NEW.TITRE,
    :NEW.DUREE, :NEW.DATE_SORTIE, :NEW.BUDGET);
END;

CREATE OR REPLACE TRIGGER DELETEDFILMS
AFTER DELETE ON FILMS
FOR EACH ROW
BEGIN
    DELETE FROM PRODUCT_CINE WHERE COD_PROD = :OLD.COD_PROD;
END;

CREATE OR REPLACE TRIGGER DELETEDFILM_ANIM
AFTER DELETE ON FILM_ANIM
FOR EACH ROW
BEGIN
    DELETE FROM PRODUCT_CINE WHERE COD_PROD = :OLD.COD_PROD;
END;

INSERT INTO FILMS(COD_PROD, TITRE, DATE_SORTIE,DUREE,BUDGET)
	SELECT (CODFILM, TITRE, DATESORTIE, DUREE, BUDGET) FROM TPBD.L2FILMS;

CREATE SEQUENCE PERSSEQ INCREMENT BY 1 START WITH 1;

CREATE VIEW NOMPERS AS SELECT DISTINCT NOMPERS FROM TPBD.L2JOUENT;

CREATE TABLE PERSONNAGES(COD_PERS, NOM_PERSO)
	AS SELECT (PERSSEQ.NEXTVAL, NOMPERS) FROM TPBD.L2JOUENT;

ALTER TABLE PERSONNAGES ADD CONSTRAINT PK_PERSONNAGES PRIMARY KEY(COD_PERS);

CREATE TABLE JOUENT (CODPROD, COD_AR, COD_PERS)
	AS SELECT CODFILM, NACT, COD_PERS FROM TPBD.L2JOUENT, PERSONNAGES WHERE (TPBDJOUENT.NOMPERS=PERSONNAGES.NOM_PERSO);

CREATE TABLE ACT_REAL (COD_AR, NOM_PERS, PRENOM_PERS, DAT_NAISS, DATE_DEC, SEXE, NATIONALITE)
	AS SELECT CODACT, NOMACT, PRENOMACT, DNAISSACT, DDECACT, SEXE, NATIONACT) FROM TPBD.L2ACTEURS;

INSERT INTO ACT_REAL (COD_AR, NOM_PERS, PRENOM_PERS, DAT_NAISS, DATE_DEC, SEXE, NATIONALITE)
	SELECT CODREAL, NOMREAL, PRENOMREAL, DNAISSREAL, DDECREAL, 'M', NATIONREAL) FROM TPBD.L2REALISATEURS;

ALTER TABLE ACT_REAL ADD CONSTRAINT FK_ACTREAL PRIMARY KEY(COD_AR);

ALTER TABLE JOUENT ADD CONSTRAINT PK_JOUENT PRIMARY KEY(CODPROD, COD_AR, COD_PERS);

ALTER TABLE JOUENT ADD CONSTRAINT FK_CODPROD_JOUENT FOREIGN KEY(COD_PROD) REFERENCES FILMS;

ALTER TABLE JOUENT ADD CONSTRAINT FK_COD_AR_JOUENT FOREIGN KEY(COD_AR) REFERENCES ACT_REAL;

ALTER TABLE JOUENT ADD CONSTRAINT FK_CODPERS_JOUENT FOREIGN KEY(COD_PERS) REFERENCES PERSONNAGES;

CREATE TABLE CONTIENT(
	COD_PROD CHAR(4),
	COD_PERS NUMBER,
	CONSTRAINT PK_CONTIENT PRIMARY KEY(COD_PROD, COD_PERS),
	CONSTRAINT FK_COD_PROD_CONTIENT FOREIGN KEY(COD_PROD) REFERENCES PRODUCT_CINE,
  CONSTRAINT FK_COD_PERS_CONTIENT FOREIGN KEY(COD_PERS) REFERENCES PERSONNAGES);

CREATE TABLE REALISE(COD_PROD, COD_AR)
	AS SELECT CODFILM, CODREAL FROM TPBD.L2FILMS;

ALTER TABLE REALISE ADD CONSTRAINT PK_JOUENT PRIMARY KEY(COD_PROD, COD_AR);

ALTER TABLE REALISE ADD CONSTRAINT FK_CODPROD_REALISE FOREIGN KEY(COD_PROD) REFERENCES FILMS;

ALTER TABLE REALISE ADD CONSTRAINT FK_COD_AR_REALISE FOREIGN KEY(COD_AR) REFERENCES ACT_REAL;

UPDATE REALISE SET COD_AR='A017' WHERE COD_AR='R008';

UPDATE REALISE SET COD_AR='A019' WHERE COD_AR='R005';

DELETE FROM REALISE WHERE COD_AR='R008';

DELETE FROM REALISE WHERE COD_AR='R005';
