/*********************Question 2***********************/

CREATE TABLE CASERNE (
  CODCAS CHAR(5),
  NOMCAS VARCHAR(50),
  ADRESSECAS VARCHAR(100),
  NBPV NUMBER(3),
  NBPP NUMBER(3),
  VILLECAS VARCHAR(50),
  CONSTRAINT PK_CASERNE PRIMARY KEY(CODCAS),
  CONSTRAINT CK_NBPV CHECK (NBPV>=0),
  CONSTRAINT CK_NBPP CHECK (NBPP>=0));

CREATE TABLE POMPIER (
  CODPOMP CHAR(5),
  NOMP VARCHAR(50),
  PRENOMP VARCHAR(50),
  DNAISSP DATE,
  GRADE NUMBER(2),
  CATEGORIE CHAR(1),
  CODCAS CHAR(5),
  CONSTRAINT PK_POMPIERS PRIMARY KEY(CODPOMP),
  CONSTRAINT FK_CODCAS_CASERNE FOREIGN KEY(CODCAS) REFERENCES CASERNE,
  CONSTRAINT CK_CATEGORIEPOMP CHECK (CATEGORIE='v' OR CATEGORIE='p')
);

CREATE TABLE INTERVENTION (
  NUMI CHAR(5),
  DATEDEB DATE,
  DATEF DATE,
  VILLEINT VARCHAR(50),
  TYPEINT VARCHAR(50),
  CONSTRAINT PK_INTERVENTION PRIMARY KEY(NUMI),
  CONSTRAINT CK_DATEF CHECK(DATEF>DATEDEB)
);

CREATE TABLE PARTICIPENT (
  CODPOMP CHAR(5),
  NUMI CHAR(5),
  CONSTRAINT FK_CODPOMP_POMPIER FOREIGN KEY(CODPOMP) REFERENCES POMPIER,
  CONSTRAINT FK_NUMI_INTERVENTION FOREIGN KEY(NUMI) REFERENCES INTERVENTION,
  CONSTRAINT PK_PARTICIPENT PRIMARY KEY(CODPOMP, NUMI));

/*********************Question 3***********************/

SELECT NOMP, PRENOMP, VILLECAS, NOMCAS
  FROM CASERNE, POMPIER
  WHERE (NBPV+NBPP)>20;

SELECT PO.NOMP, PO.PRENOMP
  FROM POMPIER PO, PARTICIPENT P
  WHERE PO.CODPOMP=P.CODPOMP
  GROUP BY PO.NOMP, PO.PRENOMP
  HAVING COUNT(DISTINCT NUMI) = (SELECT MAX(COUNT(DISTINCT P.NUMI)) FROM PARTICIPENT);

SELECT NOMCAS, CODCAS
  FROM CASERNE
  WHERE CODCAS IN (SELECT C1.CODCAS
                      FROM CASERNE C1
                      MINUS
                      (SELECT C.CODCAS
                        FROM INTERVENTION I, PARTICIPENT P, POMPIER PO, CASERNE C
                        WHERE I.TYPEINT='Incendie'
                          AND I.NUMI=P.NUMI
                          AND PO.CODPOMP=P.CODPOMP
                          AND C.CODCAS=PO.CODCAS));

SELECT COUNT(DISTINCT VILLECAS)
  FROM  CASERNE
  WHERE (NBPP)>20;

SELECT VILLEINT
  FROM INTERVENTION
  WHERE DATEF-DATEDEB = (SELECT (MAX(DATEDEB-DATEF)) FROM INTERVENTION);
